repos:
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks: [ { id: black } ]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.4
  hooks: [ { id: ruff, args: ["--fix"] } ]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-merge-conflict
    - id: end-of-file-fixer
- repo: local
  hooks:
    - id: poetry-lock-check
      name: poetry lock is in sync
      entry: bash -lc 'command -v poetry >/dev/null 2>&1 || { echo "[skip] poetry not installed"; exit 0; }; poetry check --lock || true'
      language: system
