version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: lunacore
    ports: ["5432:5432"]
    volumes: [ "db_data:/var/lib/postgresql/data" ]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  ollama:
    image: ollama/ollama:latest
    ports: ["11434:11434"]
    volumes: [ "ollama_data:/root/.ollama" ]
volumes:
  db_data: {}
  ollama_data: {}
