name: CI
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          python -m pip install --user pipx || true
          pipx install pre-commit || python -m pip install pre-commit
      - name: Run pre-commit (skip poetry-lock-check)
        env:
          SKIP: poetry-lock-check
        run: |
          pre-commit run -a
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install --user pipx || true
          pipx install poetry || python -m pip install poetry
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install deps
        run: poetry install
      - name: Pytest
        run: poetry run pytest -q
