name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Poetry
        run: pipx install poetry
      - name: Force Poetry to use runner Python
        run: poetry env use $(python -c "import sys; print(sys.executable)")
      - name: Ensure lock matches pyproject (auto-fix if needed)
        run: poetry check --lock || poetry lock --no-update
      - name: Install deps
        run: poetry install
      - name: Lint
        run: poetry run ruff check . && poetry run black --check .
      - name: Tests
        run: poetry run pytest -q --maxfail=1 --disable-warnings
