name: docs
on:
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'
      - '**/*.md'
      - 'scripts/README_exports.md'
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pre-commit
        run: pipx install pre-commit || python -m pip install pre-commit
      - name: Run pre-commit (docs-only)
        env:
          SKIP: poetry-lock-check
        run: pre-commit run -a --show-diff-on-failure
