name: Mark stale issues and PRs
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
permissions:
  issues: write
  pull-requests: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 30
          days-before-close: 7
          stale-issue-label: stale
          stale-pr-label: stale
          exempt-issue-labels: "Statut:En cours,Statut:Revue/Test,Statut:Bloqué,WIP"
          exempt-pr-labels: "Statut:En cours,Statut:Revue/Test,Statut:Bloqué,WIP"
          operations-per-run: 200
